# Form implementation generated from reading ui file 'resultsWidgetTpl.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(574, 346)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lyt_paging = QtWidgets.QHBoxLayout()
        self.lyt_paging.setObjectName("lyt_paging")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.lyt_paging.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.lyt_paging.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lyt_paging.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lyt_paging.addWidget(self.pushButton_3)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setMaximum(9999999)
        self.spinBox.setObjectName("spinBox")
        self.lyt_paging.addWidget(self.spinBox)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.lyt_paging.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lyt_paging.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.lyt_paging, 0, 0, 1, 1)
        self.view_results = QtWidgets.QTableView(Form)
        self.view_results.setStyleSheet("")
        self.view_results.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.view_results.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ContiguousSelection)
        self.view_results.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.view_results.setTextElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.view_results.setSortingEnabled(True)
        self.view_results.setObjectName("view_results")
        self.view_results.horizontalHeader().setSortIndicatorShown(True)
        self.view_results.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.view_results, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Filter by regexp"))
        self.pushButton_5.setText(_translate("Form", "Filter"))
        self.pushButton_4.setText(_translate("Form", "|<"))
        self.pushButton_3.setText(_translate("Form", "<"))
        self.pushButton.setText(_translate("Form", ">"))
        self.pushButton_2.setText(_translate("Form", ">|"))
